name: should-crash-reproduction

on:
  push:
    branches: [ "crash/*" ]

jobs:
  reproduce-internal-crash:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: OS Info
      run: uname -a
    - name: Install DynamoRIO
      run: |
        wget -q -O dynamorio.tar.gz https://github.com/DynamoRIO/dynamorio/releases/download/release_9.0.1/DynamoRIO-Linux-9.93.19503.tar.gz
        tar -xzf dynamorio.tar.gz
        export PATH=${PATH}:${PWD}/DynamoRIO-Linux-9.93.19503/bin64
        export DRIO_HOME=${PWD}/DynamoRIO-Linux-9.93.19503
    - name: Setup newer cmake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.22.1'
    - name: build
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DDynamoRIO_DIR=${PWD}/DynamoRIO-Linux-9.93.19503/cmake -S  . -B ./build && cd build && make
    - name: run hello-world client on ls binary
      run: ${PWD}/DynamoRIO-Linux-9.93.19503/bin64/drrun -c ./build/libhello_world_client.so -- /usr/bin/ls
